#include <util/delay.h>
#include "common_macros.h" /* For GET_BIT Macro */
#include "ultrasonic.h"
#include "gpio.h"
#include "icu.h"

uint8 g_edgeCount = 0;
uint16 g_timeHigh = 0;

ICU_ConfigType ICU_conf ={F_CPU_8,RAISING};
/*******************************************************************************
 *                      Functions Definitions                                  *
 *******************************************************************************/

/*
 * Description :
 * Function responsible for Initialize the ICU driver as required.
 * Set up the ICU callback function.
 * Set the direction for the trigger pin as output through the GPIO driver
*/
void Ultrasonic_init(void)
{
	ICU_init(&ICU_conf);
	ICU_setCallBack(Ultrasonic_edgeProcessing);

	GPIO_setupPinDirection(ULTRASONIC_TRIGGER_PORT_ID , ULTRASONIC_TRIGGER_PIN_ID, PIN_OUTPUT);
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT_ID, ULTRASONIC_TRIGGER_PIN_ID, LOGIC_LOW);

}

 /*
  * Description :
  * Function responsible for Send the trigger pulse to the ultrasonic sensor.
  */
void Ultrasonic_Trigger(void)
{
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT_ID, ULTRASONIC_TRIGGER_PIN_ID, LOGIC_HIGH);
	_delay_us(10);
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT_ID, ULTRASONIC_TRIGGER_PIN_ID, LOGIC_LOW);
}

/*
 * Description :
 * Function responsible for Send the trigger pulse by using the Ultrasonic_Trigger function.
 * Start the measurement process via the ICU driver
*/
uint16 Ultrasonic_readDistance(void)
{
	uint16 distance;

	Ultrasonic_Trigger();

	distance=((uint16)(g_timeHigh/117.6))+1; //in cm
	return distance;

}
/*
 * Description :
 * This is the callback function called by the ICU driver.
 * It calculates the high time (pulse time) generated by the ultrasonic sensor.
*/
void Ultrasonic_edgeProcessing(void)
{
	g_edgeCount++;
	if(g_edgeCount == 1)
	{
		/*
		 * Clear the timer counter register to start measurements from the
		 * first detected rising edge
		 */
		ICU_clearTimerValue();
		/* Detect falling edge */
		ICU_setEdgeDetectionType(FALLING);
	}
	else if(g_edgeCount == 2)
	{
		/* Store the High time value */
		g_timeHigh = ICU_getInputCaptureValue();
		/* Detect RAISING edge */
		ICU_setEdgeDetectionType(RAISING);
		g_edgeCount = 0;
	}
}
